[build]
  functions = "netlify/functions"  
  publish = "build"  

[[redirects]]
  from = "/.netlify/functions/*"
  to = ""/.netlify/functions/:splat""
  status = 200
  force = true
  headers = { "Cache-Control" = "no-cache" }

[[plugins]]
  package = "@netlify/plugin-functions-core"