# netlify.toml

[build]
  publish = "dist"
  functions = "netlify/functions"  # folder z funkcjami
  HANA_USERNAME = "your_username"
  HANA_PASSWORD = "your_password"

[[functions]]
  directory = "netlify/functions"
  external_node_modules = ["node-fetch"]

[build.environment]
  API_BASE = "https://hft71.eu/api/v1/zendesk"

[dev.environment]
  API_BASE = "http://localhost:8888/.netlify/functions"