# netlify.toml

[build]
  publish = "dist"
  functions = "netlify/functions"  # folder z funkcjami

[[edge_functions]]
  function = "handler"  # Funkcja Edge
  path = "/*"           # Obsługuje wszystkie ścieżki

[[functions]]
  function = "receive-ticket-id"  # Funkcja Lambda
  path = "/api/receive-ticket-id"  # Ścieżka do funkcji
