[build]
  functions = "netlify/functions"  
  publish = "build"  

[[redirects]]
  from = "/.netlify/functions/*"
  to = "https://dashing-churros-ab5aaa.netlify.app"
  status = 200
  force = true
  headers = { "Cache-Control" = "no-cache" }

[[plugins]]
  package = "@netlify/plugin-functions-core"